### ISSUE TITLE
[CM13][Iyokan][20160327] minor bug

### ISSUE THREAD

**Issue by fredrich** [LegacyXperia/local_manifests#1066]
thank you for developing and maintaining xperia pro port. it works great
i want to report minor bugs :
1. only see the country number : so when someone from +62 4983 4384 343 for example sent  you sms, you only see +62. unless you save the number to contact. 
2. if you want to activate data mobile you have to : turn on celular data, then make the phone in airplane mode first. then turn off airplane mode. 
3. mardon apps (MDPI_miniGAPPS-6.0-20160323-tb-signed.zip) don't work, gapps (open_gapps-arm-6.0-pico-20160410.zip) also don't work. so i installed other apps (such as bbm, whatsapp, pdf reader ) from other apk source.

i don't have logs. i am still newbie. i am sorry.

**Comment by fredrich** [comment]
here is the log :

so I try to reproduce the bug by starting Google Apps Store then I use logcat

05-06 00:02:38.147  4328  4328 W System  : ClassLoader referenced unknown path: /system/priv-app/Phonesky/lib/arm

05-06 00:02:38.292  4033  4045 I art     : Waiting for a blocking GC DisableMovingGc

05-06 00:02:38.293  4033  4043 I art     : CollectorTransition marksweep + semispace GC freed 71(-47KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 4MB/5MB, paused 62.500ms total 62.500ms

05-06 00:02:38.300  4033  4045 I art     : Starting a blocking GC DisableMovingGc

05-06 00:02:38.381  4328  4328 W Finsky.CrashDetector: Read crash info cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.381  4328  4328 W Finsky.CrashDetector: Cleanup cache cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.383  4328  4328 W Finsky.CrashDetector: Failed to delete file: /data/user/0/com.android.vending/cache/images cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.383  4328  4328 W Finsky.CrashDetector: Cleanup data stores cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.384  4328  4328 W Finsky.CrashDetector: Cleanup restore data store cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.427  4328  4328 W Finsky.CrashDetector: Cleanup installer data store cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.477  4328  4328 W Finsky  : [1] com.google.android.finsky.FinskyApp.i(1358): No account configured on this device.

05-06 00:02:38.511  4328  4328 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar

05-06 00:02:38.545  4328  4328 I Finsky  : [1] com.google.android.finsky.FinskyApp.onCreate(369): Initializing network with DFE https://android.clients.google.com/fdfe/

05-06 00:02:38.551  4328  4328 W Finsky  : [1] com.google.android.finsky.FinskyApp.i(1358): No account configured on this device.

05-06 00:02:38.554  4328  4328 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar

05-06 00:02:38.587  4328  4328 D AndroidRuntime: Shutting down VM

05-06 00:02:38.608  4328  4328 E AndroidRuntime: FATAL EXCEPTION: main

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Process: com.android.vending, PID: 4328

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Theme: themes:{}

05-06 00:02:38.608  4328  4328 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4754)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.ActivityThread.-wrap1(ActivityThread.java)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:102)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5461)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:1626)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:1573)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.content.pm.IPackageInstaller$Stub$Proxy.getMySessions(IPackageInstaller.java:385)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.content.pm.PackageInstaller.getMySessions(PackageInstaller.java:415)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at com.google.android.finsky.installer.v.<init>(SourceFile:77)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at com.google.android.finsky.FinskyApp.onCreate(SourceFile:18023)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751)

05-06 00:02:38.608  4328  4328 E AndroidRuntime:    ... 8 more

05-06 00:02:38.612   958  1765 W ActivityManager:   Force finishing activity com.android.vending/.AssetBrowserActivity

05-06 00:02:38.639   958  4350 E DropBoxManagerService: Can't write: system_app_crash

05-06 00:02:38.639   958  4350 E DropBoxManagerService: java.io.IOException: Can't list files: /data/system/dropbox

05-06 00:02:38.639   958  4350 E DropBoxManagerService:     at com.android.server.DropBoxManagerService.init(DropBoxManagerService.java:605)

05-06 00:02:38.639   958  4350 E DropBoxManagerService:     at com.android.server.DropBoxManagerService.add(DropBoxManagerService.java:186)

05-06 00:02:38.639   958  4350 E DropBoxManagerService:     at android.os.DropBoxManager.addText(DropBoxManager.java:270)

05-06 00:02:38.639   958  4350 E DropBoxManagerService:     at com.android.server.am.ActivityManagerService$19.run(ActivityManagerService.java:12877)

05-06 00:02:38.922   958  1765 I WindowManager: Screenshot max retries 4 of Token{44daa86 ActivityRecord{97aef61 u0 com.android.vending/.AssetBrowserActivity t488 f}} appWin=Window{2392999 u0 Starting com.android.vending} drawState=4

05-06 00:02:39.015   958  3581 I OpenGLRenderer: Initialized EGL, version 1.4

05-06 00:02:39.424   958   999 W ActivityManager: Activity pause timeout for ActivityRecord{97aef61 u0 com.android.vending/.AssetBrowserActivity t488 f}

05-06 00:02:39.570   958  1275 I ActivityManager: Killing 4187:com.google.process.gapps/u0a51 (adj 15): empty #9

05-06 00:02:40.049  1842  1979 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

05-06 00:02:40.308  4328  4328 I Process : Sending signal. PID: 4328 SIG: 9

05-06 00:02:40.339   958   976 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@f29eec5 attribute=null, token = android.os.BinderProxy@2c560eb

05-06 00:02:40.356   958  1862 I ActivityManager: Process com.android.vending (pid 4328) has died

05-06 00:02:40.526   958  1019 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0

**Comment by fredrich** [comment]
here is the log : 
i try to reproduce the error by starting google apps store 

05-06 00:02:38.147  4328  4328 W System  : ClassLoader referenced unknown path: /system/priv-app/Phonesky/lib/arm

05-06 00:02:38.292  4033  4045 I art     : Waiting for a blocking GC DisableMovingGc

05-06 00:02:38.293  4033  4043 I art     : CollectorTransition marksweep + semispace GC freed 71(-47KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 4MB/5MB, paused 62.500ms total 62.500ms

05-06 00:02:38.300  4033  4045 I art     : Starting a blocking GC DisableMovingGc

05-06 00:02:38.381  4328  4328 W Finsky.CrashDetector: Read crash info cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.381  4328  4328 W Finsky.CrashDetector: Cleanup cache cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.383  4328  4328 W Finsky.CrashDetector: Failed to delete file: /data/user/0/com.android.vending/cache/images cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.383  4328  4328 W Finsky.CrashDetector: Cleanup data stores cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.384  4328  4328 W Finsky.CrashDetector: Cleanup restore data store cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.427  4328  4328 W Finsky.CrashDetector: Cleanup installer data store cnt=3 ts=1462467467799 cause=java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference.

05-06 00:02:38.477  4328  4328 W Finsky  : [1] com.google.android.finsky.FinskyApp.i(1358): No account configured on this device.

05-06 00:02:38.511  4328  4328 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar

05-06 00:02:38.545  4328  4328 I Finsky  : [1] com.google.android.finsky.FinskyApp.onCreate(369): Initializing network with DFE https://android.clients.google.com/fdfe/

05-06 00:02:38.551  4328  4328 W Finsky  : [1] com.google.android.finsky.FinskyApp.i(1358): No account configured on this device.

05-06 00:02:38.554  4328  4328 W System  : ClassLoader referenced unknown path: /system/framework/tcmclient.jar

05-06 00:02:38.587  4328  4328 D AndroidRuntime: Shutting down VM

05-06 00:02:38.608  4328  4328 E AndroidRuntime: FATAL EXCEPTION: main

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Process: com.android.vending, PID: 4328

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Theme: themes:{}

05-06 00:02:38.608  4328  4328 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.finsky.FinskyApp: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4754)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.AppOpsManager.checkPackage(int, java.lang.String)' on a null object reference

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1626)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.content.pm.IPackageInstaller$Stub$Proxy.getMySessions(IPackageInstaller.java:385)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.content.pm.PackageInstaller.getMySessions(PackageInstaller.java:415)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at com.google.android.finsky.installer.v.<init>(SourceFile:77)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at com.google.android.finsky.FinskyApp.onCreate(SourceFile:18023)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751)

05-06 00:02:38.608  4328  4328 E AndroidRuntime: 	... 8 more

05-06 00:02:38.612   958  1765 W ActivityManager:   Force finishing activity com.android.vending/.AssetBrowserActivity

05-06 00:02:38.639   958  4350 E DropBoxManagerService: Can't write: system_app_crash

05-06 00:02:38.639   958  4350 E DropBoxManagerService: java.io.IOException: Can't list files: /data/system/dropbox

05-06 00:02:38.639   958  4350 E DropBoxManagerService: 	at com.android.server.DropBoxManagerService.init(DropBoxManagerService.java:605)

05-06 00:02:38.639   958  4350 E DropBoxManagerService: 	at com.android.server.DropBoxManagerService.add(DropBoxManagerService.java:186)

05-06 00:02:38.639   958  4350 E DropBoxManagerService: 	at android.os.DropBoxManager.addText(DropBoxManager.java:270)

05-06 00:02:38.639   958  4350 E DropBoxManagerService: 	at com.android.server.am.ActivityManagerService$19.run(ActivityManagerService.java:12877)

05-06 00:02:38.922   958  1765 I WindowManager: Screenshot max retries 4 of Token{44daa86 ActivityRecord{97aef61 u0 com.android.vending/.AssetBrowserActivity t488 f}} appWin=Window{2392999 u0 Starting com.android.vending} drawState=4

05-06 00:02:39.015   958  3581 I OpenGLRenderer: Initialized EGL, version 1.4

05-06 00:02:39.424   958   999 W ActivityManager: Activity pause timeout for ActivityRecord{97aef61 u0 com.android.vending/.AssetBrowserActivity t488 f}

05-06 00:02:39.570   958  1275 I ActivityManager: Killing 4187:com.google.process.gapps/u0a51 (adj 15): empty #9

05-06 00:02:40.049  1842  1979 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...

05-06 00:02:40.308  4328  4328 I Process : Sending signal. PID: 4328 SIG: 9

05-06 00:02:40.339   958   976 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@f29eec5 attribute=null, token = android.os.BinderProxy@2c560eb

05-06 00:02:40.356   958  1862 I ActivityManager: Process com.android.vending (pid 4328) has died

05-06 00:02:40.526   958  1019 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
