### ISSUE TITLE
CM13/20160417/coconut/messege app crash

### ISSUE THREAD

**Issue by warlab-zorg** [LegacyXperia/local_manifests#1077]
Messege app crash when going to -options/extended
Clear install of cm13 with full gapps only.

**Comment by peranofhome** [comment]
Hey, when you enter a message settings, Advanced Part You open up after crash

**Comment by warlab-zorg** [comment]
When I enter in advanced settings again it crashed again and again..

**Comment by piotrom87** [comment]
The same issue on Haida. "Messages">Settings>Advanced - it always gives FC.
Let's wait for the new release. Hope it will be fixed.

**Comment by derMart** [comment]
Same problem here on smultron. This is the logcat, there is a NullPointerException in the messaging app:

07-20 09:42:24.611 12913 12913 D AndroidRuntime: Shutting down VM
07-20 09:42:24.645 12913 12913 E AndroidRuntime: FATAL EXCEPTION: main
07-20 09:42:24.645 12913 12913 E AndroidRuntime: Process: com.android.messaging, PID: 12913
07-20 09:42:24.645 12913 12913 E AndroidRuntime: Theme: themes:{}
07-20 09:42:24.645 12913 12913 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.messaging/com.android.messaging.ui.appsettings.PerSubscriptionSettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual
method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5461)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
07-20 09:42:24.645 12913 12913 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.onPrepareForRemoval()' on a null object reference
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.preference.PreferenceGroup.removePreferenceInt(PreferenceGroup.java:188)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.preference.PreferenceGroup.removePreference(PreferenceGroup.java:181)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at com.android.messaging.ui.appsettings.n.onCreate(SourceFile:204)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.Fragment.performCreate(Fragment.java:2198)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.BackStackRecord.run(BackStackRecord.java:793)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.FragmentController.execPendingActions(FragmentController.java:325)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:6267)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
07-20 09:42:24.645 12913 12913 E AndroidRuntime:        ... 9 more
07-20 09:42:24.653   970  8995 W ActivityManager:   Force finishing activity com.android.messaging/.ui.appsettings.PerSubscriptionSettingsActivity
07-20 09:42:24.663   970  8995 W ActivityManager:   Force finishing activity com.android.messaging/.ui.appsettings.ApplicationSettingsActivity
