### ISSUE TITLE
[10.1] FC while editing picture in the gallery app.

### ISSUE THREAD

**Issue by mikeNG** [LegacyXperia/local_manifests#166]
To reproduce this issue you need to set sharpness to higher value and then save your picture.
Logcat: https://dl.dropboxusercontent.com/u/40426219/fcgallery.txt

 mikeNG commented 2 months ago 
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:299)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
at java.util.concurrent.FutureTask.run(FutureTask.java:239)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
at java.lang.Thread.run(Thread.java:856)
Caused by: java.lang.OutOfMemoryError
at android.graphics.Bitmap.nativeCreate(Native Method)
at android.graphics.Bitmap.createBitmap(Bitmap.java:689)
at android.graphics.Bitmap.createBitmap(Bitmap.java:666)
at android.graphics.Bitmap.createBitmap(Bitmap.java:599)
at com.android.gallery3d.filtershow.cache.ImageLoader.rotateToPortrait(ImageLoader.java:225)
at com.android.gallery3d.filtershow.tools.SaveCopyTask.loadMutableBitmap(SaveCopyTask.java:149)
at com.android.gallery3d.filtershow.tools.SaveCopyTask.doInBackground(SaveCopyTask.java:231)
at com.android.gallery3d.filtershow.tools.SaveCopyTask.doInBackground(SaveCopyTask.java:51)
at android.os.AsyncTask$2.call(AsyncTask.java:287)
at java.util.concurrent.FutureTask.run(FutureTask.java:234)
... 4 more

**Comment by Nikhildangui** [comment]
I face this issue on CM11 (nightly 20131127) -Haida
but i dint even changed sharpness just applied some effect and saved.. gallary FC destroying an nice pic from my cell

**Comment by karandpr** [comment]
What's the image size ?

**Comment by Nikhildangui** [comment]
its just default camara clicks around 1.3 MB

**Comment by karandpr** [comment]
Wanted to know the dimensions ...Check if it persists after increasing the dalvik vm size. ..
