### ISSUE TITLE
[CM11][coconut] 20140610 Trebuchet FC

### ISSUE THREAD

**Issue by azakosath** [LegacyXperia/local_manifests#656]
As the title says, Trebuchet FCs after update, even after clean installation, logcat provided:
https://gist.github.com/azakosath/d70542fba5f117c3d667

**Comment by zweif** [comment]
The same on mango. I think it was working 2 days ago.
logcat after pressing OK in force close message (and restart of Trebuchet):

```
I/Process ( 3162): Sending signal. PID: 3162 SIG: 9
I/WindowState(  598): WIN DEATH: Window{42301b00 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher}
I/ActivityManager(  598): Process com.cyanogenmod.trebuchet (pid 3162) has died.
V/Zygote  ( 3200): Switching descriptor 33 to /dev/null
V/Zygote  ( 3200): Switching descriptor 9 to /dev/null
I/ActivityManager(  598): Start proc com.cyanogenmod.trebuchet for activity com.cyanogenmod.trebuchet/com.android.launcher3.Launcher: pid=3200 uid=10006 gids={50006, 1028}
D/ActivityThread( 3200): handleBindApplication:com.cyanogenmod.trebuchet
D/ActivityThread( 3200): setTargetHeapUtilization:0.25
D/ActivityThread( 3200): setTargetHeapMinFree:524288
D/Launcher.LauncherProvider( 3200): 11683562 - initializeMaxScreenId(): 2
V/Launcher( 3200): LauncherAppState inited
E/ActivityThread( 3200): Failed to find provider info for com.android.launcher2.settings
W/Launcher( 3200): setApplicationContext called twice! old=com.android.launcher3.LauncherApplication@41af4e90 new=com.android.launcher3.LauncherApplication@41af4e90
D/Launcher.Model( 3200): 11683562 - loadWorkspace()
D/Launcher.Model( 3200): 11683562 -   loadedOldDb: false
W/Adreno-GSL( 3200): <get_panel_settings:3802>: Android framework reported version 2. So, don't force ES30
I/Adreno-EGL( 3200): <qeglDrvAPI_eglInitialize:381>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018_msm8960_KK_2.7_RB1_CL3869936_release_AU (CL3869936)
I/Adreno-EGL( 3200): OpenGL ES Shader Compiler Version: 17.01.10.SPL
I/Adreno-EGL( 3200): Build Date: 12/09/13 Mon
I/Adreno-EGL( 3200): Local Branch: mybranch2092625
I/Adreno-EGL( 3200): Remote Branch: quic/kk_2.7_rb1.15
I/Adreno-EGL( 3200): Local Patches: NONE
I/Adreno-EGL( 3200): Reconstruct Branch: AU_LINUX_ANDROID_KK_2.7_RB1.04.04.00.007.018 +  NOTHING
D/OpenGLRenderer( 3200): Enabling debug mode 0
I/ActivityManager(  598): Displayed com.cyanogenmod.trebuchet/com.android.launcher3.Launcher: +25s526ms
I/Timeline(  598): Timeline: Activity_windows_visible id: ActivityRecord{420268d0 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t4} time:3121825
W/InputMethodManagerService(  598): Got RemoteException sending setActive(false) notification to pid 3162 uid 10006
W/Binder  ( 1157): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 1157): java.lang.NullPointerException
W/Binder  ( 1157):  at android.inputmethodservice.IInputMethodWrapper.setSessionEnabled(IInputMethodWrapper.java:280)
W/Binder  ( 1157):  at com.android.internal.view.IInputMethod$Stub.onTransact(IInputMethod.java:129)
W/Binder  ( 1157):  at android.os.Binder.execTransact(Binder.java:404)
W/Binder  ( 1157):  at dalvik.system.NativeStart.run(Native Method)
I/Timeline( 3200): Timeline: Activity_idle id: android.os.BinderProxy@41aea930 time:3121871
D/Launcher.Model( 3200): 11683562 - loadWorkspaceScreensDb()
D/Launcher.Model( 3200): 11683562 -   screens: { 0: 1 }, { 1: 2 }
D/Launcher.Model( 3200): 11683562 -   sBgWorkspaceScreens: 1, 2
D/Launcher( 3200): 11683562 - bindAddScreens()
D/Launcher( 3200): 11683562 -   orderedScreenIds: 1, 2
D/Launcher.Workspace( 3200): 11683562 - insertNewWorkspaceScreen(): 1 at index: 0
D/Launcher.Workspace( 3200): 11683562 - insertNewWorkspaceScreen(): 2 at index: 1
D/Launcher.Workspace( 3200): Failed to add to item at (0,3) to CellLayout
D/AndroidRuntime( 3200): Shutting down VM
W/dalvikvm( 3200): threadid=1: thread exiting with uncaught exception (group=0x41830ce0)
E/AndroidRuntime( 3200): FATAL EXCEPTION: main
E/AndroidRuntime( 3200): Process: com.cyanogenmod.trebuchet, PID: 3200
E/AndroidRuntime( 3200): java.lang.RuntimeException: Position exceeds the bound of this CellLayout
E/AndroidRuntime( 3200):    at com.android.launcher3.CellLayout.isOccupied(CellLayout.java:3165)
E/AndroidRuntime( 3200):    at com.android.launcher3.Launcher.bindItems(Launcher.java:4095)
E/AndroidRuntime( 3200):    at com.android.launcher3.LauncherModel$LoaderTask$5.run(LauncherModel.java:2485)
E/AndroidRuntime( 3200):    at com.android.launcher3.DeferredHandler$Impl.handleMessage(DeferredHandler.java:51)
E/AndroidRuntime( 3200):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3200):    at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3200):    at android.app.ActivityThread.main(ActivityThread.java:5128)
E/AndroidRuntime( 3200):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3200):    at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3200):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
E/AndroidRuntime( 3200):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
E/AndroidRuntime( 3200):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  598):   Force finishing activity com.cyanogenmod.trebuchet/com.android.launcher3.Launcher
E/        (  598): sensors_sysfs_write: open failed! -1
E/DASH - bma250_input(  598): bma250_input_set_delay: sysfs.write_int failed!
E/        (  598): sensors_sysfs_write: open failed! -1
E/DASH - bma250_input(  598): bma250_input_set_delay: sysfs.write_int failed!
W/ActivityManager(  598): Activity pause timeout for ActivityRecord{420268d0 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t4 f}
I/ActivityManager(  598): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 cmp=com.cyanogenmod.trebuchet/com.android.launcher3.Launcher} from pid 0
D/Launcher.Model( 3200): going to save icon bitmap for info=ShortcutInfo(title=Appsintent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.camera2/com.android.camera.CameraLauncher }id=22 type=5 container=-101 screen=2 cellX=2 cellY=0 spanX=1 spanY=1 dropPos=null)
W/BackupManagerService(  598): dataChanged but no participant pkg='com.cyanogenmod.trebuchet' uid=10006
W/BackupManagerService(  598): dataChanged but no participant pkg='com.cyanogenmod.trebuchet' uid=10006
W/BackupManagerService(  598): dataChanged but no participant pkg='com.cyanogenmod.trebuchet' uid=10006
```

Someone wrote on anzu everything is fine. Could it only affect mdpi devices where the grid size is 4x3? I don't know grid size in hdpi devices.
From log above:

```
D/Launcher.Workspace( 3200): Failed to add to item at (0,3) to CellLayout
```

**Comment by c3pr3u** [comment]
The same on smultron

**Comment by ghost** [comment]
hdpi homescreen default is 4x4.

> D/Launcher.Workspace( 3200): Failed to add to item at (0,3) to CellLayout

This indeed looks suspicious.

**Comment by 16D** [comment]
I have same situation on mango with "cm-11-20140611-UNOFFICIAL-LegacyXperia-mango"

**Comment by mati865** [comment]
Hdpi devices have 4x4 grid:

# 0 1 2 3

0 X X X X
1 X X X X
2 X X X X
3 X X X X

But mdpi devices have 4x3 grid:

# 0 1 2 3

0 X X X X
1 X X X X
2 X X X X

So when launcher is trying to draw item at (0,3) it crashes because mdpi have only 3 rows (from 0 to 2). You can use different launcher until this one is fixed.

**Comment by mikeNG** [comment]
WIP fix http://review.cyanogenmod.org/#/c/65631/

**Comment by 16D** [comment]
I have used method from link:
http://forum.xda-developers.com/showpost.php?p=53339328&postcount=4752

I used CMFile Manager to edit and it works without FC.

**Comment by ksranjith786** [comment]
Can I get fix for this issue for my ANZU ? Please let me know the path to download.

**Comment by 16D** [comment]
I was using 201406010, 20140611,20140612, 20140615 on ANZU and I haven't any crash only in mango.
Yesterday i have installed this one:
http://www.androidfilehost.com/?fid=23501681358547508

**Comment by mikeNG** [comment]
Fixed in next build
