### ISSUE TITLE
[CM11][2014-10-06] NullPointer on back-navigation from WiFi-Hotspot menu

### ISSUE THREAD

**Issue by ghost** [LegacyXperia/local_manifests#808]
Reporting this for the record, but it's a CM bug.

It seems that if you turn on the WiFi hotspot and the current devices are being scanned and added to the UI (Activity) list AND while that is happening you leave  from the "WiFi-Hotspot" back into the "Tethering & portable hotspot" Menu a NullPointer reference with "Settings" Fcing is thrown.

Logcat outtake here: https://gist.github.com/Skaveelicious/765d03172078a7657fb0

But I think it can be narrowed down to this:

```
[ 10-07 19:43:00.115  7702: 7702 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.android.settings, PID: 7702
java.lang.NullPointerException
        at android.preference.Preference.<init>(Preference.java:213)
        at android.preference.Preference.<init>(Preference.java:300)
        at android.preference.Preference.<init>(Preference.java:309)
        at com.android.settings.wifi.WifiApSettings.updateClientPreferences(Wifi
ApSettings.java:149)
        at com.android.settings.wifi.WifiApSettings.access$200(WifiApSettings.ja
va:42)
        at com.android.settings.wifi.WifiApSettings$ClientUpdateHandler.handleMe
ssage(WifiApSettings.java:299)
```

I was thinking of adding an `if` statement at line 149 in `WifiApSettings.java` and only allocate if `activity` has a non `null` value. Let me know if some of you has an update to this, so no double work is done.

**Comment by ghost** [comment]
I've made a fix for this, testing and pushing to CM later.

**Comment by ghost** [comment]
Fix is working. Submitted to CM for review:
http://review.cyanogenmod.org/#/c/74856/
